### ISSUE TITLE
TypeScript errors in .d.ts for 3.0.0-0 package

### ISSUE THREAD

**Issue by buggy** [garbles/flag#13]
If I do a fresh npm install of flag 3.0.0-0 I receive the following errors when using TypeScript 2.6.1:

```
ERROR in [at-loader] ./node_modules/flag/build/flag.d.ts:13:9 
    TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

ERROR in [at-loader] ./node_modules/flag/build/flag.d.ts:13:10 
    TS2304: Cannot find name 'key'.

ERROR in [at-loader] ./node_modules/flag/build/flags-provider.d.ts:12:9 
    TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

ERROR in [at-loader] ./node_modules/flag/build/flags-provider.d.ts:12:10 
    TS2304: Cannot find name 'key'.

ERROR in [at-loader] ./node_modules/flag/build/flags-provider.d.ts:17:9 
    TS1170: A computed property name in a type literal must directly refer to a built-in symbol.

ERROR in [at-loader] ./node_modules/flag/build/flags-provider.d.ts:17:10 
    TS2304: Cannot find name 'key'.
```

I've been able to fix the problem by manually editing those definition files and changing `key` to `key: string` on the relevant lines.

**Comment by garbles** [comment]
@buggy thanks for reporting. can you open a PR with the change?

**Comment by lwih** [comment]
@buggy wanna give a try? https://github.com/unbounce/flag/pull/14

**Comment by buggy** [comment]
@lhache Thanks. That seems to fix it.

**Comment by lwih** [comment]
@garbles ready to help testing again once you merge/package a new release

**Comment by garbles** [comment]
Nice. I'll publish a new prerelease. Thanks!

**Comment by garbles** [comment]
Published as `flag@3.0.0-1`

**Comment by garbles** [comment]
@buggy LMK whether this resolves your issue and I will close this.

**Comment by lwih** [comment]
@garbles just tried out and it has fixed the issue on my side 👍

**Comment by buggy** [comment]
@garbles It seems fine now. Thanks.
