### ISSUE TITLE
Flag values fail to update when accessed within component without props 

### ISSUE THREAD

**Issue by edwardbryant** [garbles/flag#16]
I was using Flags on a recent app and I noticed the Flag component fails to work when it is called within a component that takes no props. If component A makes an API call and sets flags for FlagsProvider, then (for example) a few levels of child components are used (B, which calls C, which calls D), a flag within component D will not properly update (if D has no props). So, if the API call fetches a boolean for whether a feature is enabled, Flag within D will read it as false initially, but if the API returns true, Flag within D will not update.  

Adding an unrelated dummy prop to D (e.g., onChange={() => {}}) causes the Flag to work properly.

**Comment by garbles** [comment]
@edwardbryant can you write a failing test for this as a PR so that I can take a look?

**Comment by garbles** [comment]
Rewrote the library and I think this is probably fixed. Haven't received a failing test so I'm going to close.

https://github.com/garbles/flag/releases/tag/v4.0.0-0
