### ISSUE TITLE
Can't remove a flag

### ISSUE THREAD

**Issue by ltankey** [garbles/flag#21]
I currently use flags with redux for RN, which get persisted across app restarts. The problem is I can't:
- replace the entire value of my flags with `setFlagsAction`
- delete a single key by dispatching an action with `undefined` as the value

Perhaps I've used this wrong -- is there a way to either reset flags, or, remove individual keys explicitly as suggested [here](https://github.com/garbles/flag/pull/15#issuecomment-354366818)?

If I form an action like:
```
{
  payload: {
    features: {
      aircraftForm: undefined
    }
  },
  type: '@@FLAGS/SET_FLAGS'
}
```

I can see the action that the raw action dispatched via RN debugger is

```
{
  payload: {
    features: {}
  },
  type: '@@FLAGS/SET_FLAGS'
}
```

which doesn't achieve this.

**Comment by flexbox** [comment]
Hey @ltankey 
Did you solve your issue? If yes it could be great to share it or close the issue 😉

**Comment by ltankey** [comment]
No sadly 😔

I ended up managing flag state myself, which had a few advantages over the lib:
- I could remove flags
- changes made to flags (eg because of a config API request) wouldn't propagate using the connected provider, which meant the UX required the user to sometimes restart the app a few times to get the new flags to apply

So I just created my own flags and provided them to the flags provider as a prop passed in from a connected component.

But if it's helpful to ticket grooming here I'm happy to close this with these comments.
