### ISSUE TITLE
Return a function to execute

### ISSUE THREAD

**Issue by deniscapp** [garbles/flag#22]
I was trying to do something like this:
```
      <Flag 
        name="features.myFeature" 
        render={() => this.props.history.push(routeTo('my-route', { id: personId }))} 
        fallbackRender={() => this.props.history.push(routeTo('other-route', { id: personId }))} 
      />; 
```
It didn't work as expected, because `render` and `fallbackRender` return a `ReactElement`.
Is there a way I can make something like this to work? Or maybe this could be a new feature of `flag`?

Thanks!

**Comment by garbles** [comment]
This isn't how the library is intended to be used; however, you should return `null` from both functions. These functions are expecting a `ReactNode` to be returned.
