### ISSUE TITLE
Doesn't setup require adding reducer with value of STORE_KEY?

### ISSUE THREAD

**Issue by ezmiller** [garbles/flag#3]
I have a confusion regarding setup for this library. The README describes configuring the redux store by setting up a store enhancer. That enhancer seems to augment both the provided reducer by adding to the collection of properties a object containing the flags with the value of `STORE_KEY`, i.e. `__SUPER_SECRET_FEATURE_FLAGS__`.

This setup doesn't work as is for me because there's no reducer with the name `__SUPER_SECRET_FEATURE_FLAGS__`, so when the store dispatches the '@@/INIT` action the original (unrefined) reducer is called with a state object already packed with the feature flags, causing `combineReducers` to error saying: 

> Unexpected key "`__SUPER_SECRET_FEATURE_FLAGS__`" found in preloadedState argument passed to createStore. Expected to find one of the known reducer keys instead: .... Unexpected keys will be ignored.

The feature flags aren't copied onto the store because there's nothing to handle that piece of state. I could well be confused here, but it seems as though something is missing. Any guidance?

I was only able to get this to load properly by adding a reducer like this:

```
const __SUPER_SECRET_FEATURE_FLAGS__ = (state = {}, action) => {
  return state;
};
```

But am pretty sure that will break also at some point...

**Comment by garbles** [comment]
Hmm. I'll take a look at this in the next few days. Thanks for bring it up. Are you able to reproduce the issue with a failing test? That would really help!

**Comment by ezmiller** [comment]
I think I see the problem, can work on PR if you'd like. I also would like to contribute a component enhancer, something like `withFlag(Component, { name: "flagA", render: ..., fallbackRender ... })`.

**Comment by ezmiller** [comment]
I think basically you need this: https://github.com/zhewison/redux-feature-flags#combinationadapter.

The trouble is that if someone is using redux's `combineReducers` that function will strip out props that aren't on the main reducer.

**Comment by ezmiller** [comment]
I just tried this out locally and the thing is that it works, but you still get the unexpected key warning from `combineReducers` in dev: 

> Unexpected key "`__SUPER_SECRET_FEATURE_FLAGS__`" found in previous state received by the reducer. Expected to find one of the known reducer keys instead: "car", "searchMode", "searchParams", "searchResults", "routing". Unexpected keys will be ignored.

I'm not really sure what to think of this yet. Why does `combineReducers` assume that you'd never want to augment store data outside of what's in the main reducer?

I can see the logic in a way, in that in precisely the way your library is partly an attempt to deal with feature flag data apart from the application's main data, it is also smuggling data in such in a way that could seem like a corruption of the application's state... 

Not sure what to think about this yet. Thoughts?

**Comment by garbles** [comment]
Haven't run into someone stealing my code before. Wow.

https://github.com/zhewison/redux-feature-flags/blob/master/src/FeatureFlags.js#L3-L22

https://github.com/unbounce/react-redux-feature-flag/blob/master/src/featureFlag.js#L10-L48

**Comment by garbles** [comment]
> The trouble is that if someone is using redux's combineReducers that function will strip out props that aren't on the main reducer.

Ah you're right! Can you paste the code you used to make it throw/warn?

**Comment by ezmiller** [comment]
I literally did the same thing as in the code snippet above, from the other library. So perhaps you can steal something in turn ;). It works in terms of copying the state over more fully, in fact that's all their `combinationAdapter` does.

The trick is actually more in the unusual redux configuration in [that section of the Readme to which I linked](https://github.com/zhewison/redux-feature-flags#combinationadapter). It generates an already enhanced store creator, and then copies the state over using the combinationAdapter, feeding that into the enhanced store creator. 

If you do that, I think, you'll see the unexpected key warning. I should say that this solution seems problematic to me, bypassing the `combineReducers` attempts to keep the state clean like that seems like opening up a hole in the app a bit. But I'm not sure...just an instinct.

On another topic, I have another possibly related question for you. Why did you name the STORE_KEY string `__SUPER_SECRET_FEATURE_FLAGS__`? It actually made me wonder about the security issues here. If the flags are on the state, could someone just enable/disable them pretty easily? Did you have some something in mind in terms of hiding them?

**Comment by ezmiller** [comment]
Any progress here?

**Comment by garbles** [comment]
I have not had any time to work on this as it's not causing a problem for us. Feel free to submit a PR.

**Comment by aray12** [comment]
Couldn't you just implement this as a plain reducer, component, action creator? What is the benefit of the store enhancer? I understand that this is working for your use-case and you have no real incentive to rewrite it. But I'd like to understand your thought process before I try and rewrite and face the same issues

**Comment by garbles** [comment]
@aray12 you're right. it probably should be a reducer, component, action creator. I'd like to write a better version of this, but I just haven't had the chance.

**Comment by garbles** [comment]
The enhancer definitely does not support the general use case.

**Comment by aray12** [comment]
@garbles I really like the general concept you have presented but find the enhancer pattern a bit of a deal breaker. So I am planning on rewriting using the reducer, component, action creator pattern discussed. I will definitely cite this project as __prior art__. If you have any other requests or suggestions, please let me know. Also, if you have time and want full responsibility for the library, feel free to start and I will contribute in any way possible.

**Comment by garbles** [comment]
@aray12 @ezmiller I basically rewrote the entire thing in Typescript. I've removed the enhancer so that it now uses `combineReducers`. 🚶

**Comment by garbles** [comment]
Also renamed it to `flag`.

**Comment by garbles** [comment]
Since the implementation has completely changed, I'm going to close this for now as I'm pretty sure it's no longer an issue.

**Comment by ezmiller** [comment]
@garbles revisiting this now.
