### ISSUE TITLE
Could not find "store" in the context of "Connect(FlagsProvider)"

### ISSUE THREAD

**Issue by symbyte** [garbles/flag#30]
When attempting to integrate into my redux store I get the following error:

`Could not find "store" in the context of "Connect(FlagsProvider)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(FlagsProvider) in connect options.`

My relevant dependency versions: 
* flag@4.1.0
* react@16.8.6
* redux@4.0.1
* react-redux@7.1.0
* typescript@3.4.5

My `flags.ts`:
```typescript
import createFlags from 'flag';

export type AppFlags = {
  features: {
    queues: boolean;
    manage: boolean;
    search: boolean;
  };
  layout: {
    dragAndDrop: boolean;
  };
};

const { FlagsProvider, Flag, useFlag, useFlags } = createFlags<AppFlags>();

export { FlagsProvider, Flag, useFlag, useFlags };

import { createReduxBindings } from 'flag/redux';

const {
  setFlagsAction,
  getFlagsSelector,
  createFlagsReducer,
  ConnectedFlagsProvider,
} = createReduxBindings(FlagsProvider);

export {
  setFlagsAction,
  getFlagsSelector,
  createFlagsReducer,
  ConnectedFlagsProvider,
};
```

My `index.tsx`:
```typescript
...
import { ConnectedFlagsProvider } from './flags';
...
ReactDOM.render(
  <Provider store={store}>
    <ConnectedFlagsProvider>
      <PersistGate loading={null} persistor={persistor}>
        <App history={history} />
      </PersistGate>
    </ConnectedFlagsProvider>
  </Provider>,
  document.getElementById('root') as HTMLElement,
);
```

**Comment by symbyte** [comment]
Was able to work around this error by creating my own `ConnectedFlagsProvider` as shown below:
```typescript
...
import { FlagsProvider } from './flags';
...

const ConnectedFlagsProvider = connect((state: AppState) => ({
  flags: state.flags
}))(FlagsProvider as any)

ReactDOM.render(
  <Provider store={store}>
    <ConnectedFlagsProvider>
      <PersistGate loading={null} persistor={persistor}>
        <App history={history} />
      </PersistGate>
    </ConnectedFlagsProvider>
  </Provider>,
  document.getElementById('root') as HTMLElement,
);
````

**Comment by symbyte** [comment]
Given the above, maybe there is a bug related to when `connect` is called?

**Comment by garbles** [comment]
My only guess is the version of `react-redux` being imported by you and being imported by `flag` are different. Can you check that your lock file does not have two different versions installed? I may need to loosen the dependencies on this lib.

There is a [unit test](https://github.com/garbles/flag/blob/master/src/create-redux-bindings.test.tsx#L137) showing that your above example already works.

Thanks!

**Comment by symbyte** [comment]
I do see my direct  dependency  for `react-redux@7.1.0` as well as one for `react-redux@5.1.1`. I'm not sure how to see what caused that additional version to be installed, so I'm not sure if it was from `flag` or from something else all together.

**Comment by frnk94** [comment]
I have the same issue ! I think it related to redux-persist tho im not sure why. Had it working on a vanilla react-redux project can't seems to work inside the one who using redux-persist

**Comment by symbyte** [comment]
Ah, thats surely possible (as you have probably already noticed I am using it as well)

**Comment by emily-curry** [comment]
Could the types+react-redux in `optionalDependencies` be moved to `peerDependencies`? npm will automatically install the optional dependencies, and I don't think they're necessary unless the implementing package is using them. Ran into this today with a older version of react-redux.

**Comment by garbles** [comment]
Good to know! A PR to fix this issue are welcome!

**Comment by garbles** [comment]
Thanks @emily-curry for the PR, I've just cut a pre-release `v4.2.0-0` which you can try out and let me know if it resolves the problem here.

https://github.com/garbles/flag/releases/tag/v4.2.0-0

**Comment by emily-curry** [comment]
Sure thing! I tested this today on the project I was getting this error on, and it looks like this fixed it.

**Comment by garbles** [comment]
Good stuff. Closing this.

https://github.com/garbles/flag/releases/tag/v4.2.0
