### ISSUE TITLE
TS 3.5 error `Type instantiation is excessively deep and possibly infinite`

### ISSUE THREAD

**Issue by andreaforni** [garbles/flag#33]
Hi,
I am using your library, version `4.2.1` with TypeScript version `3.5.3` and I get the following error:

```
node_modules/flag/build/create-flags.d.ts:30:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

30     useFlag<KP extends KeyPath<T>>(keyPath: KP): KeyPathValue<T, KP>;
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by dagda1** [comment]
It is the `InternalFlattenList` coming from [useful-types](https://github.com/garbles/useful-types).

I've created this [PR](https://github.com/garbles/useful-types/pull/1) for a fix for that lib.

Really like look of flag BTW.  Great work!

**Comment by garbles** [comment]
Ah, thank you @dagda1! I'll cut a new version of `useful-types` and `flag` tonight when I've got some time.

**Comment by garbles** [comment]
@dagda1 @andreaforni published `flag@4.3.0-0`. Let me know if that fixes the error you're seeing and I'll publish `4.3.0`!

**Comment by dagda1** [comment]
That works for me.

Nice one!

Cheers

Paul Cowan

Cutting-Edge Solutions (Scotland)

blog:      http://thesoftwaresimpleton.com/
website: https://cutting.scot/

**Comment by garbles** [comment]
https://github.com/garbles/flag/releases/tag/v4.3.0
