### ISSUE TITLE
How to use without TypeScript

### ISSUE THREAD

**Issue by GlebEliseev** [garbles/flag#43]
Could you please explain to me, how to use this library without TypeScript? I am trying to follow README, but get an error.

My `flags.js`:
```
import createFlags from "flag";
import createReduxBindings from "flag/redux";

export const MyFlags = {
  logging: true
};

const { FlagsProvider, Flag, useFlag, useFlags } = createFlags(MyFlags);

export { FlagsProvider, Flag, useFlag, useFlags };


const {
  setFlagsAction,
  getFlagsSelector,
  createFlagsReducer,
  ConnectedFlagsProvider
} = createReduxBindings(FlagsProvider);

export {
  setFlagsAction,
  getFlagsSelector,
  createFlagsReducer,
  ConnectedFlagsProvider
};
```

Then, when I try to just import anything from this file as such:
`import { FlagsProvider, Flag } from "./flags";`
or
`import { createFlagsReducer, MyFlags } from "./flags";`

I get the following error:
![image](https://user-images.githubusercontent.com/13838198/85682237-c43ee680-b6d4-11ea-9a9d-12297a1e5535.png)

**Comment by garbles** [comment]
Hey @GlebEliseev, can you try change your imports to named ones?

```ts
import { createFlags } from "flag";
import { createReduxBindings } from "flag/redux";
```
