### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by paulo-propylon** [garbles/flag#56]
Can we add support to react 17? I can help with a PR, if you are okay with it.

**Comment by garbles** [comment]
Haven't updated this repo in a while, but yea feel free to open a PR and I can take a look!

**Comment by garbles** [comment]
@paulo-propylon I've updated this library so that it supports React 18+. Going to close this issue.

**Comment by AbhaySBhosale** [comment]
@garbles Is there any specific reason we are not supporting react 17, As flag is giving error if installed with react 17 and it is not easy task to updated react to 18 in application.
