### ISSUE TITLE
Flag does not support react v17. Showing peer dependancies issue as asking to install react 18

### ISSUE THREAD

**Issue by AbhaySBhosale** [garbles/flag#59]

**Comment by garbles** [comment]
This library uses `React.useExternalStore` which is a React 18 only hook. You could work around it by ignoring peer dependencies and polyfilling the hook.

**Comment by AbhaySBhosale** [comment]
@garbles We can get it working with command `npm install --legacy-peer-deps` but its not possible to always use this option with command, Expectation is flag should support react v17 and v18. Because updating to react 18 is not an easy solution as it impacts too many other libraries.

**Comment by garbles** [comment]
I'm sorry your expectation is that it should support React 17, but that's not what it supports. Feel free to open a PR.
