### ISSUE TITLE
Suggestion: Allow use of children instead of Component/Render

### ISSUE THREAD

**Issue by xml** [garbles/flag#8]
First, this is a great tool. Thank you!

Only suggestion is: it feels more intuitive to simply declare children of `Flag` as the default render: this means the least disruption to existing code when you flag it, because you're just wrapping some of your JSX template in a new component: 

```js
<Flag name="features.useMyCoolNewThing">
    <div>Rendered on truthy</div>
</Flag>
```

The remaining features/API would ideally remain the same, and anyone who prefers to use `render` could ideally still do so. But one would have the option of defaulting to the children, as above. One could also use `fallbackRender`, etc. alongside the children.

Would this be constructive? From an initial look, it seems like that would require adding the `children` prop to the `resolve()` function in `flag.tsx`, using the same basic approach to prioritizing the content options that are available...

**Comment by xml** [comment]
Note: not allowing children, and thus forcing all template into attributes/props, has the following specific consequences:

1. If you need to compose the render template with props of its own, which need `this` references, you use an arrow function. 
2. But, an arrow function binds, and it means that a new function is generated and bound on every single render of the outer component. 
3. Further, if you're using a linter config that includes `react/jsx-no-bind`, then there's literally no way to get this done without disabling the rule for each instance, or turning it off. 

REF: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

**Comment by garbles** [comment]
@xml I think this is a good idea. Code it up and add a test and I will merge it in. 😄 

I have found that the affirmative case is almost always what I'm using anyway.

**Comment by xml** [comment]
Cool. OK, can't take it on today, but will try within a week or so, if I can embrace TS that quickly 😵 ...

**Comment by garbles** [comment]
Closing because https://github.com/unbounce/flag/pull/9
